[package]
name = "backer"
version = "0.1.0"
edition = "2021"
description = "A library for straight-forward UI layout."
repository = "https://github.com/ejjonny/backer"
license = "MIT"
keywords = ["UI", "layout"]
authors = ["ejjonny"]

[lib]
crate-type = ["lib"]

[[example]]
name = "layouts"
path = "examples/layouts/src/main.rs"

[dev-dependencies]
macroquad = "0.4.13"
