[package]
name = "backer"
version = "0.1.0"
edition = "2021"

[[example]]
name = "layouts"
path = "examples/layouts/src/main.rs"

[dev-dependencies]
macroquad = "0.4.13"

[dependencies]
lilt = "0.7.0"
