name: Deploy Demo Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: "examples/demo-site"
        run: |
          set -euxo pipefail

          trunk build --release --public-url https://ejjonny.github.io/backer/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "examples/demo-site/dist"
      - name: Deploy to GitHub Pages
        # if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
