name: public-api 🌐

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check API
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Install nightly & cargo-public-api
        run: |
          set -euxo pipefail

          rustup install nightly-2024-07-05 --profile minimal
          mv ~/.rustup/toolchains/nightly-2024-07-05-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu

      - name: Install public-api
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-public-api
          locked: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Check API
        run: |
          cargo public-api diff > api_diff.txt
          cat api_diff.txt

      - name: Create comment
        if: ${{ github.event.pull_request }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```rust
            ${{ steps.check_api.outputs.api_diff }}
            ```
          token: ${{ secrets.GITHUB_TOKEN }}
