name: public-api 🌐

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check API
    runs-on: ubuntu-latest

    steps:
      - name: Install nightly & cargo-public-api
        run: |
          set -euxo pipefail

          rustup install nightly --profile minimal
          cargo +stable install cargo-public-api --locked
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo public-api diff
