name: public-api 🌐

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: check API
    runs-on: ubuntu-latest

    steps:
      - name: Install nightly & cargo-public-api
        run: |
          set -euxo pipefail

          rustup install nightly-2024-07-05 --profile minimal
          mv ~/.rustup/toolchains/nightly-2024-07-05-x86_64-unknown-linux-gnu ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
      - name: Install public-api
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-public-api
          locked: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo public-api diff
